/**
 * Daftar Kota dan Kabupaten di Indonesia untuk pilihan Tempat Lahir
 * Terdiri dari kota-kota utama dan kabupaten di seluruh wilayah Indonesia.
 */

export interface IndonesianCityGroup {
  region: string;
  cities: string[];
}

export const INDONESIAN_CITIES_BY_REGION: IndonesianCityGroup[] = [
  {
    region: "DKI Jakarta",
    cities: [
      "Jakarta Barat",
      "Jakarta Pusat",
      "Jakarta Selatan",
      "Jakarta Timur",
      "Jakarta Utara",
      "Kepulauan Seribu",
    ],
  },
  {
    region: "Jawa Barat",
    cities: [
      "Kota Bandung",
      "Kota Banjar",
      "Kota Bekasi",
      "Kota Bogor",
      "Kota Cimahi",
      "Kota Cirebon",
      "Kota Depok",
      "Kota Sukabumi",
      "Kota Tasikmalaya",
      "Kab. Bandung",
      "Kab. Bandung Barat",
      "Kab. Bekasi",
      "Kab. Bogor",
      "Kab. Ciamis",
      "Kab. Cianjur",
      "Kab. Cirebon",
      "Kab. Garut",
      "Kab. Indramayu",
      "Kab. Karawang",
      "Kab. Kuningan",
      "Kab. Majalengka",
      "Kab. Pangandaran",
      "Kab. Purwakarta",
      "Kab. Subang",
      "Kab. Sukabumi",
      "Kab. Sumedang",
      "Kab. Tasikmalaya",
    ],
  },
  {
    region: "Banten",
    cities: [
      "Kota Cilegon",
      "Kota Serang",
      "Kota Tangerang",
      "Kota Tangerang Selatan",
      "Kab. Lebak",
      "Kab. Pandeglang",
      "Kab. Serang",
      "Kab. Tangerang",
    ],
  },
  {
    region: "Jawa Tengah",
    cities: [
      "Kota Magelang",
      "Kota Pekalongan",
      "Kota Salatiga",
      "Kota Semarang",
      "Kota Surakarta (Solo)",
      "Kota Tegal",
      "Kab. Banjarnegara",
      "Kab. Banyumas",
      "Kab. Batang",
      "Kab. Blora",
      "Kab. Boyolali",
      "Kab. Brebes",
      "Kab. Cilacap",
      "Kab. Demak",
      "Kab. Grobogan",
      "Kab. Jepara",
      "Kab. Karanganyar",
      "Kab. Kebumen",
      "Kab. Kendal",
      "Kab. Klaten",
      "Kab. Kudus",
      "Kab. Magelang",
      "Kab. Pati",
      "Kab. Pekalongan",
      "Kab. Pemalang",
      "Kab. Purbalingga",
      "Kab. Purworejo",
      "Kab. Rembang",
      "Kab. Semarang",
      "Kab. Sragen",
      "Kab. Sukoharjo",
      "Kab. Tegal",
      "Kab. Temanggung",
      "Kab. Wonogiri",
      "Kab. Wonosobo",
    ],
  },
  {
    region: "DI Yogyakarta",
    cities: [
      "Kota Yogyakarta",
      "Kab. Bantul",
      "Kab. Gunungkidul",
      "Kab. Kulon Progo",
      "Kab. Sleman",
    ],
  },
  {
    region: "Jawa Timur",
    cities: [
      "Kota Batu",
      "Kota Blitar",
      "Kota Kediri",
      "Kota Madiun",
      "Kota Malang",
      "Kota Mojokerto",
      "Kota Pasuruan",
      "Kota Probolinggo",
      "Kota Surabaya",
      "Kab. Bangkalan",
      "Kab. Banyuwangi",
      "Kab. Blitar",
      "Kab. Bojonegoro",
      "Kab. Bondowoso",
      "Kab. Gresik",
      "Kab. Jember",
      "Kab. Jombang",
      "Kab. Kediri",
      "Kab. Lamongan",
      "Kab. Lumajang",
      "Kab. Madiun",
      "Kab. Magetan",
      "Kab. Malang",
      "Kab. Mojokerto",
      "Kab. Nganjuk",
      "Kab. Ngawi",
      "Kab. Pacitan",
      "Kab. Pamekasan",
      "Kab. Pasuruan",
      "Kab. Ponorogo",
      "Kab. Probolinggo",
      "Kab. Sampang",
      "Kab. Sidoarjo",
      "Kab. Situbondo",
      "Kab. Sumenep",
      "Kab. Trenggalek",
      "Kab. Tuban",
      "Kab. Tulungagung",
    ],
  },
  {
    region: "Sumatera",
    cities: [
      "Kota Banda Aceh",
      "Kota Bandar Lampung",
      "Kota Batam",
      "Kota Bengkulu",
      "Kota Binjai",
      "Kota Bukittinggi",
      "Kota Dumai",
      "Kota Jambi",
      "Kota Langsa",
      "Kota Lhokseumawe",
      "Kota Lubuklinggau",
      "Kota Medan",
      "Kota Metro",
      "Kota Padang",
      "Kota Padang Sidempuan",
      "Kota Pagar Alam",
      "Kota Palembang",
      "Kota Pangkalpinang",
      "Kota Pariaman",
      "Kota Payakumbuh",
      "Kota Pekanbaru",
      "Kota Pematangsiantar",
      "Kota Prabumulih",
      "Kota Sabang",
      "Kota Sibolga",
      "Kota Singkawang",
      "Kota Solok",
      "Kota Subulussalam",
      "Kota Tanjungbalai",
      "Kota Tanjungpinang",
      "Kota Tebing Tinggi",
      "Kab. Agam",
      "Kab. Asahan",
      "Kab. Deli Serdang",
      "Kab. Kampar",
      "Kab. Lampung Selatan",
      "Kab. Ogan Ilir",
      "Kab. Ogan Komering Ilir",
      "Kab. Tanah Datar",
    ],
  },
  {
    region: "Bali & Nusa Tenggara",
    cities: [
      "Kota Denpasar",
      "Kota Mataram",
      "Kota Bima",
      "Kota Kupang",
      "Kab. Badung",
      "Kab. Bangli",
      "Kab. Buleleng",
      "Kab. Gianyar",
      "Kab. Jembrana",
      "Kab. Karangasem",
      "Kab. Klungkung",
      "Kab. Tabanan",
      "Kab. Lombok Barat",
      "Kab. Lombok Tengah",
      "Kab. Lombok Timur",
      "Kab. Lombok Utara",
      "Kab. Sumbawa",
      "Kab. Manggarai Barat (Labuan Bajo)",
      "Kab. Sikka (Maumere)",
    ],
  },
  {
    region: "Kalimantan",
    cities: [
      "Kota Balikpapan",
      "Kota Banjarmasin",
      "Kota Banjarbaru",
      "Kota Bontang",
      "Kota Palangka Raya",
      "Kota Pontianak",
      "Kota Samarinda",
      "Kota Singkawang",
      "Kota Tarakan",
      "Kab. Berau",
      "Kab. Banjar",
      "Kab. Ketapang",
      "Kab. Kotawaringin Barat",
      "Kab. Kutai Kartanegara",
    ],
  },
  {
    region: "Sulawesi",
    cities: [
      "Kota Bau-Bau",
      "Kota Bitung",
      "Kota Gorontalo",
      "Kota Kendari",
      "Kota Kotamobagu",
      "Kota Makassar",
      "Kota Manado",
      "Kota Palopo",
      "Kota Palu",
      "Kota Parepare",
      "Kota Tomohon",
      "Kab. Bone",
      "Kab. Gowa",
      "Kab. Maros",
      "Kab. Minahasa",
      "Kab. Toraja",
    ],
  },
  {
    region: "Maluku & Papua",
    cities: [
      "Kota Ambon",
      "Kota Jayapura",
      "Kota Sorong",
      "Kota Ternate",
      "Kota Tidore Kepulauan",
      "Kab. Biak Numfor",
      "Kab. Fakfak",
      "Kab. Manokwari",
      "Kab. Merauke",
      "Kab. Mimika (Timika)",
      "Kab. Nabire",
    ],
  },
];

/**
 * Daftar flat seluruh kota/kabupaten yang sudah diurutkan abjad
 */
export const ALL_INDONESIAN_CITIES: string[] = Array.from(
  new Set(INDONESIAN_CITIES_BY_REGION.flatMap((g) => g.cities))
).sort((a, b) => a.localeCompare(b, "id"));

/**
 * Daftar pekerjaan umum orang tua/wali di Indonesia
 */
export const INDONESIAN_PARENT_JOBS: string[] = [
  "Pegawai Negeri Sipil (PNS)",
  "Pegawai Pemerintah (PPPK)",
  "Guru / Dosen",
  "TNI / POLRI",
  "Karyawan BUMN / BUMD",
  "Karyawan Swasta",
  "Wiraswasta / Pengusaha",
  "Pedagang / Pemilik Toko",
  "Dokter / Bidan / Perawat / Tenaga Medis",
  "Petani / Peternak / Pekebun",
  "Nelayan / Sektor Kelautan",
  "Buruh Harian / Pekerja Lepas",
  "Pengemudi / Driver Online / Logistik",
  "Teknisi / Mekanik",
  "Advokat / Notaris / Konsultan",
  "Arsitek / Insinyur",
  "Seniman / Desainer / Kreator Konten",
  "Ibu Rumah Tangga (IRT)",
  "Pensiunan",
  "Tidak Bekerja",
  "Lainnya"
];

